name: CD Build
env:
  REPOSITORY: pranaysahith
  IMAGE: icap-adaptation-service
  TAG: main

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: cd cmd && go build -v .
    - name: Test
      run: go test -v ./cmd
  
  build-push-docker-image:
    name: Build and Push Docker Image
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: pranaysahith
        password: ${{ secrets.ICAPDOCKERSECRET }}
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7} -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest .
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE }}

    - name: yq - portable yaml processor
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Check out icap-infrastructure repo
      uses: actions/checkout@v2
      with:
        repository: 'pranaysahith/icap-infrastructure'
        token: ${{ secrets.GITHUBTOKEN }}
        path: infra
    - name: Update image tag in icap-infrastructure repo
      run: |
        # git clone https://pranaysahith:$GITHUB_TOKEN@github.com/pranaysahith/icap-infrastructure.git
        # cd icap-infrastructure
        cd infra
        IMAGE_TAG=${{ env.TAG }}-${GITHUB_SHA::7}
        git checkout -b $IMAGE_TAG
        git config user.email github-actions@github.com
        git config user.name github-actions
        # update imagestore.adaptationservice.tag value in the values.yaml file
        yq write adaptation/values.yaml imagestore.adaptationservice.tag $IMAGE_TAG -i
        git add adaptation/values.yaml
        git commit -m 'update image tag'
        git push origin $IMAGE_TAG
        gh pr create --base main --title "Update adaptationservice image tag to $IMAGE_TAG" --body ""
        sleep 5s
        gh pr merge $IMAGE_TAG -s
        # cd .. && rm -rf icap-infrastructure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
