name: CD Build
env:
  REPOSITORY: pranaysahith
  IMAGE: icap-adaptation-service
  TAG: main

on:
  push:
    branches: 
      - develop

jobs:
  build-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - uses: fregante/setup-git-user@v1
    - name: Update image tag in icap-infrastructure repo
      run: |
        gh repo clone pranaysahith/icap-infrastructure
        rm -rf icap-infrastructure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
